name: Test

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Which Python
      run: which python

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.6

    - name: venv
      run: |
        python -m venv benv
        source benv/bin/activate

    - name: which python with venv
      run: |
        source benv/bin/activate
        which python


    - name: Which Python
      run: which python
